name: Docker build images with docker
on:
  push:
    branches:
    - 'main'
jobs:
  find-dockerfiles:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Find changed Dockerfiles
        id: find-dockerfiles
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'Dockerfile')
          echo "Changed Dockerfiles: $files"
          echo "::set-output name=dockerfiles::${files}"

      - name: Create JSON matrix for the strategy
        id: set-matrix
        run: |
          dockerfiles="${{ steps.find-dockerfiles.outputs.dockerfiles }}"
          json_matrix="{\"include\": ["
          for file in $dockerfiles; do
            dir=$(dirname $file)
            json_matrix="$json_matrix {\"dockerfile\": \"$file\", \"context\": \"$dir\"},"
          done
          json_matrix="${json_matrix%,}]}"
          echo "Matrix: $json_matrix"
          echo "::set-output name=matrix::$json_matrix"
  build-docker:
    needs: find-dockerfiles
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.find-dockerfiles.outputs.matrix)}}   
    permissions:
      contents: read
      packages: write
    
    steps:

    - name: Checkout
      uses: actions/checkout@v4
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        push: ${{ env.PUSH == 'true' && true || false }}
        tags: ghcr.io/${{ github.repository }}/${{ matrix.context }}:${{ github.sha }}
