name: Docker build images with docker
on:
  push:
    branches:
    - 'main'
env:
  APP_NAME: 'reprepro'
  TAG: '5.3.0-1.3'

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare variables
      run: |
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
        echo "REGISTRY=ghcr.io" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build temp image
      run: |
        APP_NAME=reprepro
        BASE_IMAGE="$REGISTRY/$GITHUB_REPOSITORY/$APP_NAME"
        LATEST_IMAGE="$BASE_IMAGE:latest"
        cd $APP_NAME
        docker build . -t $LATEST_IMAGE

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.APP_NAME }}
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/builder:${{ env.APP_NAME }}-${{ env.TAG }}-${{github.run_number}}