name: Docker build images with docker
on:
  push:
    branches:
    - 'main/**'
jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare variables
      run: |
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
        echo "REGISTRY=ghcr.io" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build temp net-snmp-aes image
      if: ${{ env.IMAGE != 'exist' }}
      run: |
        APP_NAME=net-snmp-aes
        BASE_IMAGE="$REGISTRY/$GITHUB_REPOSITORY/$APP_NAME"
        LATEST_IMAGE="$BASE_IMAGE:latest"
        cd $APP_NAME
        docker build . -t $LATEST_IMAGE
        docker push $LATEST_IMAGE